# Generated by Django 4.0.6 on 2022-07-19 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(help_text='This image will shown on list and feed preview', upload_to='media/')),
                ('image_2', models.ImageField(help_text='This image will shown on list and feed preview', upload_to='media/')),
                ('image_3', models.ImageField(help_text='This image will shown on list and feed preview', upload_to='media/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 19, 12, 45, 8, 668038), null=True)),
            ],
        ),
    ]
