# Generated by Django 4.0.6 on 2022-07-21 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('positon', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=500)),
                ('image', models.ImageField(help_text='This image will shown on list and feed preview', upload_to='media/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 11, 44, 28, 429551), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 21, 11, 44, 28, 428552), null=True),
        ),
    ]
