# Generated by Django 4.0.6 on 2022-07-23 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projects_website_alter_projects_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='industry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='service',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 4, 27, 31, 944291), null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 4, 27, 31, 944291), null=True),
        ),
    ]
