# Generated by Django 4.0.6 on 2022-07-23 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_projects_created_at_alter_projects_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='case_study',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 4, 32, 59, 928828), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 23, 4, 32, 59, 928828), null=True),
        ),
    ]
