# Generated by Django 4.0.6 on 2022-08-01 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_projects_case_study_alter_projects_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 47, 36, 332299), null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='positon',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='review',
            name='image',
        ),
        migrations.AddField(
            model_name='projects',
            name='logo',
            field=models.ImageField(default='media/dummy.jpeg', help_text='Project Company logo', upload_to='media/'),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.projects'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 47, 36, 331644), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 47, 36, 332039), null=True),
        ),
    ]
