# Generated by Django 4.0.6 on 2022-08-01 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contact_rename_positon_review_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 48, 1, 401055), null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 48, 1, 400416), null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 2, 1, 48, 1, 400803), null=True),
        ),
    ]
