# Generated by Django 4.0.6 on 2022-08-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_contact_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
