# Generated by Django 4.0.6 on 2022-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_projects_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='image_2',
            new_name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='image_3',
        ),
        migrations.AddField(
            model_name='projects',
            name='technology',
            field=models.ManyToManyField(to='home.technology'),
        ),
    ]
