# Generated by Django 4.0.6 on 2022-08-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_projects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='case_study',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
